[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

# SPA Fallback Redirect for React Router & client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
